//
//  ChatWireframe.swift
//  Botter
//
//  Created by Nora on 6/3/20.
//  Copyright (c) 2020 BlueCrunch. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ChatWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = ChatViewController.instantiateFromStoryBoard(appStoryBoard: .Main)
        super.init(viewController: moduleViewController)

        let interactor = ChatInteractor()
        let presenter = ChatPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }

}

// MARK: - Extensions -

extension ChatWireframe: ChatWireframeInterface {
    
    func openVideo(url: String) {
        
    }
    
    func openUrl(url: String) {
//        WebLinksViewController.openInParent(link: url, parent: self.viewController)
        if let url = URL(string: "url") {
            UIApplication.shared.open(url)
        }
    }
    
    func call(number: String) {
        self.viewController.makePhoneCall(phoneNumber: number)
    }
}
