//
//  ChatPresenter.swift
//  Botter
//
//  Created by Nora on 6/3/20.
//  Copyright (c) 2020 BlueCrunch. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ChatPresenter {

    // MARK: - Private properties -

    private unowned let view: ChatViewInterface
    private let interactor: ChatInteractorInterface
    private let wireframe: ChatWireframeInterface

    var messgesList : [BasicMessage]!
    
    // MARK: - Lifecycle -

    init(view: ChatViewInterface, interactor: ChatInteractorInterface, wireframe: ChatWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.messgesList = [BasicMessage]()
    }
}

// MARK: - Extensions -

extension ChatPresenter: ChatPresenterInterface {
    func openSocket() {
        self.interactor.openSocket()
    }
    
    func messageReceived(message: BasicMessage) {
        messgesList.append(message)
        self.view.reload()
    }
    
    func sendMessage(text: String) {
        self.interactor.sendMessage(text: text)
    }
    
    func clearTextBox() {
        self.view.clearTextBox()
    }
    
    func showError(errorMsg: String) {
        self.view.showError(errorMsg: errorMsg)
    }
    
    func openVideo(url: String) {
        self.wireframe.openVideo(url: url)
    }
    
    func actionClicked(action: Action) {
        interactor.actionClicked(action: action)
    }
    
    func openUrl(url: String) {
        wireframe.openUrl(url: url)
    }
    
    func call(number: String) {
        wireframe.call(number: number)
    }
    
}
