//
//  ChatInterfaces.swift
//  Botter
//
//  Created by Nora on 6/3/20.
//  Copyright (c) 2020 BlueCrunch. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ChatWireframeInterface: WireframeInterface {
    func openVideo(url : String)
    func openUrl(url : String)
    func call(number: String)
    func openEndForm(form : b_Form , isHistory : Bool)
}

protocol ChatViewInterface: b_ViewInterface {
    func reload()
    func clearTextBox()
    func showError(errorMsg : String)
    func connectionUpdated(isConnected : Bool)
    
}

protocol ChatPresenterInterface: b_PresenterInterface {
    var messgesList : [b_BasicMessage]! { get set }
    func openSocket()
    func messageReceived(message : b_BasicMessage)
    func historyLoaded(list : [b_BasicMessage])
    func sendMessage(text : String)
    func clearTextBox()
    func showError(errorMsg : String)
    func openVideo(url : String)
    func actionClicked(action : b_Action)
    func openUrl(url : String)
    func call(number: String)
    func triviaActionClicked(action: b_Action)
    func resend(msg : b_BasicMessage)
    func openEndForm(form : b_Form , isHistory : Bool)
    func sendMenuAction(action : b_MenuItem)
    func sendAttachment(file : b_AttachedFile)
    func sendUserLocation(latitude : Double, langtuide: Double)
    func endSession()
}

protocol ChatInteractorInterface: b_InteractorInterface {
    func openSocket()
    func sendMessage(text : String , completion:@escaping((b_BasicMessage)->()))
    func actionClicked(action : b_Action)
    func triviaMessage(action : b_Action , completion:@escaping((b_BasicMessage)->()))
    func resend(msg: b_BasicMessage , completion:@escaping((Bool)->()))
    func sendMenuAction(action : b_MenuItem ,completion:@escaping((b_BasicMessage)->()))
    func sendAttachment(file : b_AttachedFile,completion:@escaping((b_BasicMessage)->()))
    func sendUserLocation(latitude : Double, langtuide: Double ,completion:@escaping((b_BasicMessage)->()))
    func endSession()
}
