//
//  ChatInteractor.swift
//  Botter
//
//  Created by Nora on 6/3/20.
//  Copyright (c) 2020 BlueCrunch. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class b_ChatInteractor {
    var presenter: ChatPresenterInterface!
}

// MARK: - Extensions -

extension b_ChatInteractor: ChatInteractorInterface {
    
    func openSocket() {
        B_SocketManager.shared.connect()
        B_SocketManager.shared.messageRecieved = { msg in
            self.presenter.messageReceived(message: msg)
        }
        B_SocketManager.shared.historyLoaded = { list in
            var mList = list
            mList.removeAll(where: {$0.slug.lowercased() == ""})
//            mList.removeAll(where: {$0.type.lowercased() == "welcome_back"})
//            mList.removeAll(where: {$0.type.lowercased() == "set_attributes"})
            if mList.count > 0 {
                self.presenter.historyLoaded(list: mList)
            }
            
        }
    }
    
    func resend(msg: b_BasicMessage , completion:@escaping((Bool)->()))  {
        
        if B_SocketManager.shared.isConnected && b_ReachabilityManager.shared.isNetworkAvailable{
            if msg.blockValue != ""{
                B_SocketManager.shared.sendMessage(text: msg.blockValue) { (isSent) in
                    completion(isSent)
                }
            }else{
                B_SocketManager.shared.sendMessage(text: msg.text){ (isSent) in
                    completion(isSent)
                }
            }
             
        }else{
            B_SocketManager.shared.connect()
            completion(false)
        }
    }
    
    func sendMessage(text : String , completion:@escaping((b_BasicMessage)->())){
        let Message = b_BasicMessage()
        Message.type = "message"
        Message.isBotMsg = false
        Message.text = text
        Message.slug = "message"
        Message.msgType = .userMsg
        Message.sender.senderType = .user
        self.presenter.clearTextBox()
        
        if B_SocketManager.shared.isConnected{
            B_SocketManager.shared.sendMessage(text: text){ isSent in
                completion(Message)
            }
        }else{
            B_SocketManager.shared.connect()
            Message.msgSent = false
            completion(Message)
        }
        
    }
    
    func triviaMessage(action : b_Action , completion:@escaping((b_BasicMessage)->())){
        let Message = b_BasicMessage()
        Message.type = "message"
        Message.slug = "message"
        Message.isBotMsg = false
        Message.text = action.title
        Message.msgType = .userMsg
        Message.sender.senderType = .user
        if B_SocketManager.shared.isConnected{
            if action.action == .date{
                B_SocketManager.shared.sendMessage(text: action.title) { (isSent) in
                    completion(Message)
                }
            }else{
                B_SocketManager.shared.sendPostBack(value: action.value , title: action.title , slug: Message.slug){ isSent in
                    completion(Message)
                }
            }
//            return true
        }else{
            B_SocketManager.shared.connect()
            Message.msgSent = false
//            return false
            Message.blockValue = action.value
            completion(Message)
        }
//        self.presenter.messageReceived(message: Message)
   
    }
    
    func actionClicked(action: b_Action) {
        switch action.action {
        case .call:
            presenter.call(number: action.value)
            break
        case .openUrl:
            presenter.openUrl(url: action.value)
            break
        case .postBack:
            B_SocketManager.shared.sendPostBack(value: action.value , title: action.title , completion: { isSent in
//                completion(isSent)
            })
            break
        default:
            break
        }
    }
    
    func sendAttachment(file: b_AttachedFile, completion:@escaping((b_BasicMessage)->())) {
        let Message = b_BasicMessage()
        Message.type = "attachment"
        Message.isBotMsg = false
        Message.mediaUrl = file.url
        Message.type = file.type
        Message.text = file.name
        Message.slug = file.type == "image" ? "image_attachment" : "attachment"
        Message.sender.senderType = .user
        Message.msgType = b_MessageType.init(rawValue: Message.slug) ?? .attachment
        
        if B_SocketManager.shared.isConnected{
            B_SocketManager.shared.sendAttachment(file: file, completion: { (isSent) in
                completion(Message)
            })
        }else{
            B_SocketManager.shared.connect()
            Message.msgSent = false
            completion(Message)
        }
    }
    
    func sendMenuAction(action : b_MenuItem ,completion:@escaping((b_BasicMessage)->())){
        let Message = b_BasicMessage()
        Message.type = "message"
        Message.slug = "message"
        Message.isBotMsg = false
        Message.text = action.title
        Message.msgType = .userMsg
        Message.sender.senderType = .user
        if B_SocketManager.shared.isConnected{
            B_SocketManager.shared.sendPostBack(value: action.payload , title: action.title , slug:Message.slug ){ isSent in
                completion(Message)
            }
        }else{
            B_SocketManager.shared.connect()
            Message.msgSent = false
            //            return false
            Message.blockValue = action.payload
            completion(Message)
        }
    }
    
    func sendUserLocation(latitude : Double ,langtuide langtude : Double, completion:@escaping((b_BasicMessage)->())){
          let Message = b_BasicMessage()
          Message.type = "message"
          Message.isBotMsg = false
          Message.latitude = latitude
          Message.langtude = langtude
          Message.slug = "user_location"
          Message.msgType = .userLocation
          Message.sender.senderType = .user
          self.presenter.clearTextBox()
          
          if B_SocketManager.shared.isConnected{
              B_SocketManager.shared.sendUserLocation(latitude: latitude, langtude: langtude) { isSent in
                  completion(Message)
              }
          }else{
              B_SocketManager.shared.connect()
              Message.msgSent = false
              completion(Message)
          }
    }
    
    func endSession() {
        B_SocketManager.shared.endSession()
    }
        
}
