//
//  StartFormViewController.swift
//  Botter
//
//  Created by Nora on 7/15/20.
//  Copyright (c) 2020 BlueCrunch. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class StartFormViewController: StartConversationViewController {

    // MARK: - Public properties -
    @IBOutlet weak var tableView : UITableView!

    var presenter: StartFormPresenterInterface!

    var loader = LoaderManager()
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.loadForms()
    }
    
    override func newConversationClicked() {
        self.presenter.validateThenSubmitForm()
    }

}

// MARK: - Extensions -

extension StartFormViewController: StartFormViewInterface {
    func showLoader() {
        self.loader.show(inRect: self.view.frame, inView: self.view)
    }
    
    func hideLoader() {
        self.loader.remove()
    }
    
    func reload() {
        self.tableView.reloadData()
    }
}

extension StartFormViewController : UITableViewDataSource{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.presenter.dataCells.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return self.presenter.dataCells[indexPath.row]
    }
}
