//
//  StartFormWireframe.swift
//  Botter
//
//  Created by Nora on 7/15/20.
//  Copyright (c) 2020 BlueCrunch. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class StartFormWireframe: b_BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = b_StartFormViewController.b_instantiateFromStoryBoard(appStoryBoard: .Forms)
        super.init(viewController: moduleViewController)

        let interactor = StartFormInteractor()
        let presenter = StartFormPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }

}

// MARK: - Extensions -

extension StartFormWireframe: StartFormWireframeInterface {
    func openChat(data:b_BotData) {
        CommonActions.openChat(parent: self.viewController, data: data)
    }
}
