//
//  StartFormInteractor.swift
//  Botter
//
//  Created by Nora on 7/15/20.
//  Copyright (c) 2020 BlueCrunch. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

final class StartFormInteractor {
     var presenter: StartFormPresenterInterface!
}

// MARK: - Extensions -

extension StartFormInteractor: StartFormInteractorInterface {
    func loadForms() {
        self.presenter.showLoader()
        let dataSource = BotterDataSource()
        dataSource.getBotterData { (status, response) in
            self.presenter.hideLoader()
            self.presenter.botData = response as? BotData ?? BotData()
            self.presenter.getCells()
        }
    }
    
    func validateForm(){
        var isValid = true
        for cell in self.presenter.dataCells{
            if let mCell = cell as? BasicFormTableViewCell{
                isValid = mCell.validateFormInput() && isValid
            }
        }
        
        if isValid {
            submitForm()
        }
    }
    
    func submitForm(){
        var attributes = [[String : Any]]()
        for cell in self.presenter.dataCells{
            if let mCell = cell as? BasicFormTableViewCell{
                var tAttribute = [String : Any]()
                tAttribute["attribute"] = mCell.input.key
                tAttribute["value"] = mCell.getAnswer()
                attributes.append(tAttribute)
            }
        }
        
        SocketManager.shared.attributes = attributes
        self.presenter.openChat()
        
    }
}
