//
//  StartFormInterfaces.swift
//  Botter
//
//  Created by Nora on 7/15/20.
//  Copyright (c) 2020 BlueCrunch. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol StartFormWireframeInterface: WireframeInterface {
    func openChat(data:BotData)
}

protocol StartFormViewInterface: ViewInterface {
    func showLoader()
    func hideLoader()
     func reload()
}

protocol StartFormPresenterInterface: PresenterInterface {
    var botData : BotData! { get set }
    var dataCells : [UITableViewCell]! { get set }
    func loadForms()
    func showLoader()
    func hideLoader()
    func reload()
    func getCells()
    func validateThenSubmitForm()
    func openChat()
}

protocol StartFormInteractorInterface: InteractorInterface {
    func loadForms()
    func validateForm()
    
}
