// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreGraphics;
@import Foundation;
@import MediaPlayer;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Botter",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif




/// An <code>AudioItem</code> instance contains every piece of information needed for an <code>AudioPlayer</code> to play.
/// URLs can be remote or local.
SWIFT_CLASS("_TtC6Botter9AudioItem")
@interface AudioItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




/// An <code>AudioPlayer</code> instance is used to play <code>AudioPlayerItem</code>. It’s an easy to use AVPlayer with simple methods to
/// handle the whole playing audio process.
/// You can get events (such as state change or time observation) by registering a delegate.
SWIFT_CLASS("_TtC6Botter11AudioPlayer")
@interface AudioPlayer : NSObject
/// Initializes a new AudioPlayer.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end























@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC6Botter34BotterControllerWithHiddenLauncher")
@interface BotterControllerWithHiddenLauncher : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Botter17ContentHeaderView")
@interface ContentHeaderView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL isTranslucent;
@end

@protocol ContentSheetContentProtocol;
@class UIImage;
enum ContentSheetState : NSUInteger;
@protocol ContentSheetDelegate;
@class UINavigationBar;
@class UINavigationItem;
@protocol UIViewControllerTransitioningDelegate;

SWIFT_CLASS("_TtC6Botter12ContentSheet")
@interface ContentSheet : UIViewController
@property (nonatomic, readonly, strong) id <ContentSheetContentProtocol> _Nonnull content;
@property (nonatomic, strong) UIImage * _Nullable backgroundImage;
@property (nonatomic, strong) UIView * _Nullable backgroundView;
@property (nonatomic) BOOL blurBackground;
@property (nonatomic) enum UIBlurEffectStyle blurStyle;
@property (nonatomic) BOOL dismissOnTouchOutside;
@property (nonatomic) BOOL handleKeyboard;
@property (nonatomic) BOOL enablePanGesture;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) enum ContentSheetState state;
@property (nonatomic, weak) id <ContentSheetDelegate> _Nullable delegate;
@property (nonatomic) BOOL showDefaultHeader;
@property (nonatomic, readonly, strong) UINavigationBar * _Nullable contentNavigationBar;
@property (nonatomic, readonly, strong) UIView * _Nullable contentHeader;
@property (nonatomic, readonly, strong) UINavigationItem * _Nullable contentNavigationItem;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithContent:(id <ContentSheetContentProtocol> _Nonnull)content OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
@property (nonatomic, strong) id <UIViewControllerTransitioningDelegate> _Nullable transitioningDelegate;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) UIStatusBarAnimation preferredStatusBarUpdateAnimation;
- (void)resetContentSheetHeightWithCollapsedHeight:(CGFloat)collapsedHeight expandedHeight:(CGFloat)expandedHeight;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ContentSheet (SWIFT_EXTENSION(Botter))
+ (ContentSheet * _Nullable)contentSheetWithContent:(id <ContentSheetContentProtocol> _Nonnull)content SWIFT_WARN_UNUSED_RESULT;
@end

@protocol UIBarPositioning;

@interface ContentSheet (SWIFT_EXTENSION(Botter)) <UINavigationBarDelegate>
- (UIBarPosition)positionForBar:(id <UIBarPositioning> _Nonnull)bar SWIFT_WARN_UNUSED_RESULT;
@end

@class UIGestureRecognizer;

@interface ContentSheet (SWIFT_EXTENSION(Botter)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end


@interface ContentSheet (SWIFT_EXTENSION(Botter))
- (void)willMoveToParentViewController:(UIViewController * _Nullable)parent;
- (void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
@end

@class UITouch;
@class UIEvent;

@interface ContentSheet (SWIFT_EXTENSION(Botter))
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end

@protocol UIViewControllerContextTransitioning;

SWIFT_CLASS("_TtC6Botter20ContentSheetAnimator")
@interface ContentSheetAnimator : NSObject <UIViewControllerAnimatedTransitioning>
@property (nonatomic) NSTimeInterval duration;
@property (nonatomic) BOOL presenting;
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

SWIFT_PROTOCOL("_TtP6Botter27ContentSheetContentProtocol_")
@protocol ContentSheetContentProtocol
@property (nonatomic, readonly, strong) UIView * _Null_unspecified view;
@optional
@property (nonatomic, readonly, strong) UINavigationItem * _Nonnull navigationItem;
- (void)contentSheetWillAddContent:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetDidAddContent:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetWillRemoveContent:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetDidRemoveContent:(ContentSheet * _Nonnull)sheet;
- (CGFloat)collapsedHeightWithContainedIn:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)expandedHeightWithContainedIn:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nullable)scrollViewToObserveWithContainedIn:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (BOOL)prefersStatusBarHiddenWithContentSheet:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UIStatusBarStyle)preferredStatusBarStyleWithContentSheet:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UIStatusBarAnimation)preferredStatusBarUpdateAnimationWithContentSheet:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP6Botter20ContentSheetDelegate_")
@protocol ContentSheetDelegate
@optional
- (void)contentSheetWillAppear:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetDidAppear:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetWillDisappear:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetDidDisappear:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetWillShow:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetDidShow:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetWillHide:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetDidHide:(ContentSheet * _Nonnull)sheet;
@end

@protocol UIContentContainer;

SWIFT_CLASS("_TtC6Botter34ContentSheetPresentationController")
@interface ContentSheetPresentationController : UIPresentationController
- (void)presentationTransitionWillBegin;
- (void)presentationTransitionDidEnd:(BOOL)completed;
- (void)dismissalTransitionWillBegin;
- (void)dismissalTransitionDidEnd:(BOOL)completed;
- (void)containerViewWillLayoutSubviews;
- (CGSize)sizeForChildContentContainer:(id <UIContentContainer> _Nonnull)container withParentContainerSize:(CGSize)parentSize SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) CGRect frameOfPresentedViewInContainerView;
- (nonnull instancetype)initWithPresentedViewController:(UIViewController * _Nonnull)presentedViewController presentingViewController:(UIViewController * _Nullable)presentingViewController OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSUInteger, ContentSheetState, open) {
  ContentSheetStateMinimised = 0,
  ContentSheetStateCollapsed = 1,
  ContentSheetStateExpanded = 2,
};


SWIFT_CLASS("_TtC6Botter30ContentSheetTransitionDelegate")
@interface ContentSheetTransitionDelegate : NSObject <UIViewControllerTransitioningDelegate>
@property (nonatomic) NSTimeInterval duration;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
- (UIPresentationController * _Nullable)presentationControllerForPresentedViewController:(UIViewController * _Nonnull)presented presentingViewController:(UIViewController * _Nullable)presenting sourceViewController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class NSStream;

SWIFT_CLASS("_TtC6Botter19FoundationTransport")
@interface FoundationTransport : NSObject <NSStreamDelegate>
- (void)stream:(NSStream * _Nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Botter13GradientHView")
@interface GradientHView : UIView
@property (nonatomic, strong) IBInspectable UIColor * _Nullable color1;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable color2;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC6Botter12GradientView")
@interface GradientView : UIView
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull startColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull endColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end





@class NSURLSession;
@class NSURLSessionWebSocketTask;

SWIFT_CLASS("_TtC6Botter12NativeEngine") SWIFT_AVAILABILITY(tvos,introduced=13.0) SWIFT_AVAILABILITY(watchos,introduced=6.0) SWIFT_AVAILABILITY(ios,introduced=13.0) SWIFT_AVAILABILITY(macos,introduced=10.15)
@interface NativeEngine : NSObject <NSURLSessionDataDelegate, NSURLSessionWebSocketDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session webSocketTask:(NSURLSessionWebSocketTask * _Nonnull)webSocketTask didOpenWithProtocol:(NSString * _Nullable)protocol;
- (void)URLSession:(NSURLSession * _Nonnull)session webSocketTask:(NSURLSessionWebSocketTask * _Nonnull)webSocketTask didCloseWithCode:(NSURLSessionWebSocketCloseCode)closeCode reason:(NSData * _Nullable)reason;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;

SWIFT_PROTOCOL("_TtP6Botter17SwiftyGifDelegate_")
@protocol SwiftyGifDelegate
@optional
- (void)gifDidStartWithSender:(UIImageView * _Nonnull)sender;
- (void)gifDidLoopWithSender:(UIImageView * _Nonnull)sender;
- (void)gifDidStopWithSender:(UIImageView * _Nonnull)sender;
- (void)gifURLDidFinishWithSender:(UIImageView * _Nonnull)sender;
- (void)gifURLDidFailWithSender:(UIImageView * _Nonnull)sender url:(NSURL * _Nonnull)url error:(NSError * _Nullable)error;
@end




































@interface UINavigationController (SWIFT_EXTENSION(Botter))
@property (nonatomic, readonly, strong) UIViewController * _Nullable childViewControllerForStatusBarStyle;
@end




@interface UINavigationController (SWIFT_EXTENSION(Botter))
- (CGFloat)collapsedHeightWithContainedIn:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)expandedHeightWithContainedIn:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nullable)scrollViewToObserveWithContainedIn:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (BOOL)prefersStatusBarHiddenWithContentSheet:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UIStatusBarStyle)preferredStatusBarStyleWithContentSheet:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UIStatusBarAnimation)preferredStatusBarUpdateAnimationWithContentSheet:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
@end










@interface UITabBarController (SWIFT_EXTENSION(Botter))
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@end








@interface UITextView (SWIFT_EXTENSION(Botter)) <UITextViewDelegate>
@end








@interface UIView (SWIFT_EXTENSION(Botter))
@property (nonatomic, readonly, strong) UIView * _Nullable firstResponder;
@end


@interface UIView (SWIFT_EXTENSION(Botter)) <ContentSheetContentProtocol>
@property (nonatomic, readonly, strong) UIView * _Null_unspecified view;
- (void)dismissContentSheetWithAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (ContentSheet * _Nullable)contentSheet SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIView (SWIFT_EXTENSION(Botter))
- (void)awakeFromNib;
@end






@interface UIViewController (SWIFT_EXTENSION(Botter)) <ContentSheetContentProtocol>
- (ContentSheet * _Nullable)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UINavigationBar * _Nullable)cs_navigationBar SWIFT_WARN_UNUSED_RESULT;
- (void)contentSheetWillAddContent:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetDidAddContent:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetWillRemoveContent:(ContentSheet * _Nonnull)sheet;
- (void)contentSheetDidRemoveContent:(ContentSheet * _Nonnull)sheet;
- (CGFloat)collapsedHeightWithContainedIn:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (BOOL)prefersStatusBarHiddenWithContentSheet:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UIStatusBarStyle)preferredStatusBarStyleWithContentSheet:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UIStatusBarAnimation)preferredStatusBarUpdateAnimationWithContentSheet:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)expandedHeightWithContainedIn:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nullable)scrollViewToObserveWithContainedIn:(ContentSheet * _Nonnull)contentSheet SWIFT_WARN_UNUSED_RESULT;
- (void)presentInContentSheet:(id <ContentSheetContentProtocol> _Nonnull)content animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)dismissContentSheetWithAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
@end





#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
